language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:
 - npm install -g typescript@2.4.2
 - npm cache verify
 - npm install -g @angular/cli@1.5.3
 - npm install -g yarn
 - npm install
 - dotnet restore --verbosity m
 - dotnet build