language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:
 - npm install -g typescript
 - npm cache verify
 - npm install -g @angular/cli
 - npm install -g yarn
 - npm install
 - dotnet restore --verbosity m
 - dotnet build